kind: Service
apiVersion: v1
metadata:
  name: processor
  labels:
    app: processor
spec:
  type: ClusterIP
  selector:
    app: processor
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
        version: v1
    spec:
      containers:
      - name: processor
        image: processor
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
