kind: Service
apiVersion: v1
metadata:
  name: scraper
  labels:
    app: scraper
spec:
  type: ClusterIP
  selector:
    app: scraper
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
        version: v1
    spec:
      containers:
      - name: scraper
        image: scraper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
