server:
  host: 0.0.0.0
  port: 8082

neo4j:
  uri: ${NEO4J_URL:bolt://localhost:7687}
  authentication:
    username: neo4j
    password: your_password

exist-db/mp-rest/url: ${EXIST_DB_URL:http://localhost:8080}